//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 04-10-2016 19:00:25
namespace testClient.Org.Naima.Services.Cases.Models
{
    /// <summary>
    /// There are no comments for CaseSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CaseSingle")]
    public partial class CaseSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Case>
    {
        /// <summary>
        /// Initialize a new CaseSingle object.
        /// </summary>
        public CaseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CaseSingle object.
        /// </summary>
        public CaseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CaseSingle object.
        /// </summary>
        public CaseSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Case> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Patient")]
        public global::testClient.Org.Naima.Services.Cases.Models.PatientSingle Patient
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Patient == null))
                {
                    this._Patient = new global::testClient.Org.Naima.Services.Cases.Models.PatientSingle(this.Context, GetPath("Patient"));
                }
                return this._Patient;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.PatientSingle _Patient;
        /// <summary>
        /// There are no comments for Doctor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Doctor")]
        public global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle Doctor
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Doctor == null))
                {
                    this._Doctor = new global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle(this.Context, GetPath("Doctor"));
                }
                return this._Doctor;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle _Doctor;
        /// <summary>
        /// There are no comments for CareProvider in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CareProvider")]
        public global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle CareProvider
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CareProvider == null))
                {
                    this._CareProvider = new global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle(this.Context, GetPath("CareProvider"));
                }
                return this._CareProvider;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle _CareProvider;
    }
    /// <summary>
    /// There are no comments for Case in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Case")]
    public partial class Case : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Case object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Case CreateCase(int ID)
        {
            Case @case = new Case();
            @case.Id = ID;
            return @case;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PatientId")]
        public global::System.Nullable<int> PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this._PatientId = value;
                this.OnPatientIdChanged();
                this.OnPropertyChanged("PatientId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _PatientId;
        partial void OnPatientIdChanging(global::System.Nullable<int> value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Property DoctorId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DoctorId")]
        public global::System.Nullable<int> DoctorId
        {
            get
            {
                return this._DoctorId;
            }
            set
            {
                this.OnDoctorIdChanging(value);
                this._DoctorId = value;
                this.OnDoctorIdChanged();
                this.OnPropertyChanged("DoctorId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _DoctorId;
        partial void OnDoctorIdChanging(global::System.Nullable<int> value);
        partial void OnDoctorIdChanged();
        /// <summary>
        /// There are no comments for Property CareProviderId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CareProviderId")]
        public global::System.Nullable<int> CareProviderId
        {
            get
            {
                return this._CareProviderId;
            }
            set
            {
                this.OnCareProviderIdChanging(value);
                this._CareProviderId = value;
                this.OnCareProviderIdChanged();
                this.OnPropertyChanged("CareProviderId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _CareProviderId;
        partial void OnCareProviderIdChanging(global::System.Nullable<int> value);
        partial void OnCareProviderIdChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Patient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Patient")]
        public global::testClient.Org.Naima.Services.Cases.Models.Patient Patient
        {
            get
            {
                return this._Patient;
            }
            set
            {
                this.OnPatientChanging(value);
                this._Patient = value;
                this.OnPatientChanged();
                this.OnPropertyChanged("Patient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.Patient _Patient;
        partial void OnPatientChanging(global::testClient.Org.Naima.Services.Cases.Models.Patient value);
        partial void OnPatientChanged();
        /// <summary>
        /// There are no comments for Property Doctor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Doctor")]
        public global::testClient.Org.Naima.Services.Cases.Models.Doctor Doctor
        {
            get
            {
                return this._Doctor;
            }
            set
            {
                this.OnDoctorChanging(value);
                this._Doctor = value;
                this.OnDoctorChanged();
                this.OnPropertyChanged("Doctor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.Doctor _Doctor;
        partial void OnDoctorChanging(global::testClient.Org.Naima.Services.Cases.Models.Doctor value);
        partial void OnDoctorChanged();
        /// <summary>
        /// There are no comments for Property CareProvider in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CareProvider")]
        public global::testClient.Org.Naima.Services.Cases.Models.CareProvider CareProvider
        {
            get
            {
                return this._CareProvider;
            }
            set
            {
                this.OnCareProviderChanging(value);
                this._CareProvider = value;
                this.OnCareProviderChanged();
                this.OnPropertyChanged("CareProvider");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.CareProvider _CareProvider;
        partial void OnCareProviderChanging(global::testClient.Org.Naima.Services.Cases.Models.CareProvider value);
        partial void OnCareProviderChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PatientSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PatientSingle")]
    public partial class PatientSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Patient>
    {
        /// <summary>
        /// Initialize a new PatientSingle object.
        /// </summary>
        public PatientSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PatientSingle object.
        /// </summary>
        public PatientSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PatientSingle object.
        /// </summary>
        public PatientSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Patient> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::testClient.Org.Naima.Services.Cases.Models.LocationSingle Location
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Location == null))
                {
                    this._Location = new global::testClient.Org.Naima.Services.Cases.Models.LocationSingle(this.Context, GetPath("Location"));
                }
                return this._Location;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.LocationSingle _Location;
        /// <summary>
        /// There are no comments for Cases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cases")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> Cases
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Cases == null))
                {
                    this._Cases = Context.CreateQuery<global::testClient.Org.Naima.Services.Cases.Models.Case>(GetPath("Cases"));
                }
                return this._Cases;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> _Cases;
    }
    /// <summary>
    /// There are no comments for Patient in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Patient")]
    public partial class Patient : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Patient CreatePatient(int ID)
        {
            Patient patient = new Patient();
            patient.Id = ID;
            return patient;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property LocationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationId")]
        public global::System.Nullable<int> LocationId
        {
            get
            {
                return this._LocationId;
            }
            set
            {
                this.OnLocationIdChanging(value);
                this._LocationId = value;
                this.OnLocationIdChanged();
                this.OnPropertyChanged("LocationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _LocationId;
        partial void OnLocationIdChanging(global::System.Nullable<int> value);
        partial void OnLocationIdChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::testClient.Org.Naima.Services.Cases.Models.Location Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.Location _Location;
        partial void OnLocationChanging(global::testClient.Org.Naima.Services.Cases.Models.Location value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Cases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cases")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> Cases
        {
            get
            {
                return this._Cases;
            }
            set
            {
                this.OnCasesChanging(value);
                this._Cases = value;
                this.OnCasesChanged();
                this.OnPropertyChanged("Cases");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> _Cases = new global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCasesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> value);
        partial void OnCasesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DoctorSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DoctorSingle")]
    public partial class DoctorSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Doctor>
    {
        /// <summary>
        /// Initialize a new DoctorSingle object.
        /// </summary>
        public DoctorSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DoctorSingle object.
        /// </summary>
        public DoctorSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DoctorSingle object.
        /// </summary>
        public DoctorSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Doctor> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::testClient.Org.Naima.Services.Cases.Models.LocationSingle Location
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Location == null))
                {
                    this._Location = new global::testClient.Org.Naima.Services.Cases.Models.LocationSingle(this.Context, GetPath("Location"));
                }
                return this._Location;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.LocationSingle _Location;
        /// <summary>
        /// There are no comments for Cases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cases")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> Cases
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Cases == null))
                {
                    this._Cases = Context.CreateQuery<global::testClient.Org.Naima.Services.Cases.Models.Case>(GetPath("Cases"));
                }
                return this._Cases;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> _Cases;
    }
    /// <summary>
    /// There are no comments for Doctor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Doctor")]
    public partial class Doctor : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Doctor object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Doctor CreateDoctor(int ID)
        {
            Doctor doctor = new Doctor();
            doctor.Id = ID;
            return doctor;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property LocationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationId")]
        public global::System.Nullable<int> LocationId
        {
            get
            {
                return this._LocationId;
            }
            set
            {
                this.OnLocationIdChanging(value);
                this._LocationId = value;
                this.OnLocationIdChanged();
                this.OnPropertyChanged("LocationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _LocationId;
        partial void OnLocationIdChanging(global::System.Nullable<int> value);
        partial void OnLocationIdChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::testClient.Org.Naima.Services.Cases.Models.Location Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.Location _Location;
        partial void OnLocationChanging(global::testClient.Org.Naima.Services.Cases.Models.Location value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Cases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cases")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> Cases
        {
            get
            {
                return this._Cases;
            }
            set
            {
                this.OnCasesChanging(value);
                this._Cases = value;
                this.OnCasesChanged();
                this.OnPropertyChanged("Cases");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> _Cases = new global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCasesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> value);
        partial void OnCasesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CareProviderSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CareProviderSingle")]
    public partial class CareProviderSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CareProvider>
    {
        /// <summary>
        /// Initialize a new CareProviderSingle object.
        /// </summary>
        public CareProviderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CareProviderSingle object.
        /// </summary>
        public CareProviderSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CareProviderSingle object.
        /// </summary>
        public CareProviderSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CareProvider> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::testClient.Org.Naima.Services.Cases.Models.LocationSingle Location
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Location == null))
                {
                    this._Location = new global::testClient.Org.Naima.Services.Cases.Models.LocationSingle(this.Context, GetPath("Location"));
                }
                return this._Location;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.LocationSingle _Location;
        /// <summary>
        /// There are no comments for Cases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cases")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> Cases
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Cases == null))
                {
                    this._Cases = Context.CreateQuery<global::testClient.Org.Naima.Services.Cases.Models.Case>(GetPath("Cases"));
                }
                return this._Cases;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> _Cases;
    }
    /// <summary>
    /// There are no comments for CareProvider in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CareProvider")]
    public partial class CareProvider : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CareProvider object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static CareProvider CreateCareProvider(int ID)
        {
            CareProvider careProvider = new CareProvider();
            careProvider.Id = ID;
            return careProvider;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property LocationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LocationId")]
        public global::System.Nullable<int> LocationId
        {
            get
            {
                return this._LocationId;
            }
            set
            {
                this.OnLocationIdChanging(value);
                this._LocationId = value;
                this.OnLocationIdChanged();
                this.OnPropertyChanged("LocationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _LocationId;
        partial void OnLocationIdChanging(global::System.Nullable<int> value);
        partial void OnLocationIdChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
        public global::testClient.Org.Naima.Services.Cases.Models.Location Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::testClient.Org.Naima.Services.Cases.Models.Location _Location;
        partial void OnLocationChanging(global::testClient.Org.Naima.Services.Cases.Models.Location value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Cases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cases")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> Cases
        {
            get
            {
                return this._Cases;
            }
            set
            {
                this.OnCasesChanging(value);
                this._Cases = value;
                this.OnCasesChanged();
                this.OnPropertyChanged("Cases");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> _Cases = new global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCasesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::testClient.Org.Naima.Services.Cases.Models.Case> value);
        partial void OnCasesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LocationSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("LocationSingle")]
    public partial class LocationSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Location>
    {
        /// <summary>
        /// Initialize a new LocationSingle object.
        /// </summary>
        public LocationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LocationSingle object.
        /// </summary>
        public LocationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LocationSingle object.
        /// </summary>
        public LocationSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Location> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Location in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Location")]
    public partial class Location : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Location CreateLocation(int ID)
        {
            Location location = new Location();
            location.Id = ID;
            return location;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Locality in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Locality")]
        public string Locality
        {
            get
            {
                return this._Locality;
            }
            set
            {
                this.OnLocalityChanging(value);
                this._Locality = value;
                this.OnLocalityChanged();
                this.OnPropertyChanged("Locality");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Locality;
        partial void OnLocalityChanging(string value);
        partial void OnLocalityChanged();
        /// <summary>
        /// There are no comments for Property SubDistrict in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SubDistrict")]
        public string SubDistrict
        {
            get
            {
                return this._SubDistrict;
            }
            set
            {
                this.OnSubDistrictChanging(value);
                this._SubDistrict = value;
                this.OnSubDistrictChanged();
                this.OnPropertyChanged("SubDistrict");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _SubDistrict;
        partial void OnSubDistrictChanging(string value);
        partial void OnSubDistrictChanged();
        /// <summary>
        /// There are no comments for Property District in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("District")]
        public string District
        {
            get
            {
                return this._District;
            }
            set
            {
                this.OnDistrictChanging(value);
                this._District = value;
                this.OnDistrictChanged();
                this.OnPropertyChanged("District");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _District;
        partial void OnDistrictChanging(string value);
        partial void OnDistrictChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.Case as global::testClient.Org.Naima.Services.Cases.Models.CaseSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.CaseSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::testClient.Org.Naima.Services.Cases.Models.CaseSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.Case as global::testClient.Org.Naima.Services.Cases.Models.CaseSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.CaseSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::testClient.Org.Naima.Services.Cases.Models.CaseSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.Patient as global::testClient.Org.Naima.Services.Cases.Models.PatientSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.PatientSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Patient> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::testClient.Org.Naima.Services.Cases.Models.PatientSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.Patient as global::testClient.Org.Naima.Services.Cases.Models.PatientSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.PatientSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Patient> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::testClient.Org.Naima.Services.Cases.Models.PatientSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.Doctor as global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Doctor> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.Doctor as global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Doctor> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::testClient.Org.Naima.Services.Cases.Models.DoctorSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.CareProvider as global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.CareProvider> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.CareProvider as global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.CareProvider> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::testClient.Org.Naima.Services.Cases.Models.CareProviderSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.Location as global::testClient.Org.Naima.Services.Cases.Models.LocationSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.LocationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Location> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::testClient.Org.Naima.Services.Cases.Models.LocationSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::testClient.Org.Naima.Services.Cases.Models.Location as global::testClient.Org.Naima.Services.Cases.Models.LocationSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::testClient.Org.Naima.Services.Cases.Models.LocationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Location> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::testClient.Org.Naima.Services.Cases.Models.LocationSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace testClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Org.Naima.Services.Cases.Models", "testClient.Org.Naima.Services.Cases.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "testClient.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("testClient.Org.Naima.Services.Cases.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Org.Naima.Services.Cases.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Org.Naima.Services.Cases.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("testClient.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Cases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cases")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> Cases
        {
            get
            {
                if ((this._Cases == null))
                {
                    this._Cases = base.CreateQuery<global::testClient.Org.Naima.Services.Cases.Models.Case>("Cases");
                }
                return this._Cases;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Case> _Cases;
        /// <summary>
        /// There are no comments for Patients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Patients")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Patient> Patients
        {
            get
            {
                if ((this._Patients == null))
                {
                    this._Patients = base.CreateQuery<global::testClient.Org.Naima.Services.Cases.Models.Patient>("Patients");
                }
                return this._Patients;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Patient> _Patients;
        /// <summary>
        /// There are no comments for Doctors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Doctors")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Doctor> Doctors
        {
            get
            {
                if ((this._Doctors == null))
                {
                    this._Doctors = base.CreateQuery<global::testClient.Org.Naima.Services.Cases.Models.Doctor>("Doctors");
                }
                return this._Doctors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Doctor> _Doctors;
        /// <summary>
        /// There are no comments for CareProviders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CareProviders")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.CareProvider> CareProviders
        {
            get
            {
                if ((this._CareProviders == null))
                {
                    this._CareProviders = base.CreateQuery<global::testClient.Org.Naima.Services.Cases.Models.CareProvider>("CareProviders");
                }
                return this._CareProviders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.CareProvider> _CareProviders;
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Locations")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Location> Locations
        {
            get
            {
                if ((this._Locations == null))
                {
                    this._Locations = base.CreateQuery<global::testClient.Org.Naima.Services.Cases.Models.Location>("Locations");
                }
                return this._Locations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::testClient.Org.Naima.Services.Cases.Models.Location> _Locations;
        /// <summary>
        /// There are no comments for Cases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCases(global::testClient.Org.Naima.Services.Cases.Models.Case @case)
        {
            base.AddObject("Cases", @case);
        }
        /// <summary>
        /// There are no comments for Patients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToPatients(global::testClient.Org.Naima.Services.Cases.Models.Patient patient)
        {
            base.AddObject("Patients", patient);
        }
        /// <summary>
        /// There are no comments for Doctors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToDoctors(global::testClient.Org.Naima.Services.Cases.Models.Doctor doctor)
        {
            base.AddObject("Doctors", doctor);
        }
        /// <summary>
        /// There are no comments for CareProviders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCareProviders(global::testClient.Org.Naima.Services.Cases.Models.CareProvider careProvider)
        {
            base.AddObject("CareProviders", careProvider);
        }
        /// <summary>
        /// There are no comments for Locations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToLocations(global::testClient.Org.Naima.Services.Cases.Models.Location location)
        {
            base.AddObject("Locations", location);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Org.Naima.Services.Cases.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Case"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""PatientId"" Type=""Edm.Int32"" />
        <Property Name=""DoctorId"" Type=""Edm.Int32"" />
        <Property Name=""CareProviderId"" Type=""Edm.Int32"" />
        <Property Name=""Status"" Type=""Edm.String"" />
        <NavigationProperty Name=""Patient"" Type=""Org.Naima.Services.Cases.Models.Patient"">
          <ReferentialConstraint Property=""PatientId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Doctor"" Type=""Org.Naima.Services.Cases.Models.Doctor"">
          <ReferentialConstraint Property=""DoctorId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""CareProvider"" Type=""Org.Naima.Services.Cases.Models.CareProvider"">
          <ReferentialConstraint Property=""CareProviderId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""Patient"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""LocationId"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Location"" Type=""Org.Naima.Services.Cases.Models.Location"">
          <ReferentialConstraint Property=""LocationId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Cases"" Type=""Collection(Org.Naima.Services.Cases.Models.Case)"" />
      </EntityType>
      <EntityType Name=""Doctor"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""LocationId"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Location"" Type=""Org.Naima.Services.Cases.Models.Location"">
          <ReferentialConstraint Property=""LocationId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Cases"" Type=""Collection(Org.Naima.Services.Cases.Models.Case)"" />
      </EntityType>
      <EntityType Name=""CareProvider"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""LocationId"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Location"" Type=""Org.Naima.Services.Cases.Models.Location"">
          <ReferentialConstraint Property=""LocationId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Cases"" Type=""Collection(Org.Naima.Services.Cases.Models.Case)"" />
      </EntityType>
      <EntityType Name=""Location"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Locality"" Type=""Edm.String"" />
        <Property Name=""SubDistrict"" Type=""Edm.String"" />
        <Property Name=""District"" Type=""Edm.String"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Cases"" EntityType=""Org.Naima.Services.Cases.Models.Case"">
          <NavigationPropertyBinding Path=""Patient"" Target=""Patients"" />
          <NavigationPropertyBinding Path=""Doctor"" Target=""Doctors"" />
          <NavigationPropertyBinding Path=""CareProvider"" Target=""CareProviders"" />
        </EntitySet>
        <EntitySet Name=""Patients"" EntityType=""Org.Naima.Services.Cases.Models.Patient"">
          <NavigationPropertyBinding Path=""Location"" Target=""Locations"" />
          <NavigationPropertyBinding Path=""Cases"" Target=""Cases"" />
        </EntitySet>
        <EntitySet Name=""Doctors"" EntityType=""Org.Naima.Services.Cases.Models.Doctor"">
          <NavigationPropertyBinding Path=""Location"" Target=""Locations"" />
          <NavigationPropertyBinding Path=""Cases"" Target=""Cases"" />
        </EntitySet>
        <EntitySet Name=""CareProviders"" EntityType=""Org.Naima.Services.Cases.Models.CareProvider"">
          <NavigationPropertyBinding Path=""Location"" Target=""Locations"" />
          <NavigationPropertyBinding Path=""Cases"" Target=""Cases"" />
        </EntitySet>
        <EntitySet Name=""Locations"" EntityType=""Org.Naima.Services.Cases.Models.Location"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
