/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.naima.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Case extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Case\",\"namespace\":\"org.naima.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"patient\",\"type\":{\"type\":\"record\",\"name\":\"patientRecord\",\"fields\":[{\"name\":\"locality\",\"type\":\"string\"},{\"name\":\"subdistrict\",\"type\":\"string\"},{\"name\":\"district\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public org.naima.avro.patientRecord patient;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Case() {}

  /**
   * All-args constructor.
   */
  public Case(java.lang.CharSequence id, org.naima.avro.patientRecord patient) {
    this.id = id;
    this.patient = patient;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return patient;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: patient = (org.naima.avro.patientRecord)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'patient' field.
   */
  public org.naima.avro.patientRecord getPatient() {
    return patient;
  }

  /**
   * Sets the value of the 'patient' field.
   * @param value the value to set.
   */
  public void setPatient(org.naima.avro.patientRecord value) {
    this.patient = value;
  }

  /** Creates a new Case RecordBuilder */
  public static org.naima.avro.Case.Builder newBuilder() {
    return new org.naima.avro.Case.Builder();
  }
  
  /** Creates a new Case RecordBuilder by copying an existing Builder */
  public static org.naima.avro.Case.Builder newBuilder(org.naima.avro.Case.Builder other) {
    return new org.naima.avro.Case.Builder(other);
  }
  
  /** Creates a new Case RecordBuilder by copying an existing Case instance */
  public static org.naima.avro.Case.Builder newBuilder(org.naima.avro.Case other) {
    return new org.naima.avro.Case.Builder(other);
  }
  
  /**
   * RecordBuilder for Case instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Case>
    implements org.apache.avro.data.RecordBuilder<Case> {

    private java.lang.CharSequence id;
    private org.naima.avro.patientRecord patient;

    /** Creates a new Builder */
    private Builder() {
      super(org.naima.avro.Case.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.naima.avro.Case.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.patient)) {
        this.patient = data().deepCopy(fields()[1].schema(), other.patient);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Case instance */
    private Builder(org.naima.avro.Case other) {
            super(org.naima.avro.Case.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.patient)) {
        this.patient = data().deepCopy(fields()[1].schema(), other.patient);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public org.naima.avro.Case.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public org.naima.avro.Case.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'patient' field */
    public org.naima.avro.patientRecord getPatient() {
      return patient;
    }
    
    /** Sets the value of the 'patient' field */
    public org.naima.avro.Case.Builder setPatient(org.naima.avro.patientRecord value) {
      validate(fields()[1], value);
      this.patient = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'patient' field has been set */
    public boolean hasPatient() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'patient' field */
    public org.naima.avro.Case.Builder clearPatient() {
      patient = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Case build() {
      try {
        Case record = new Case();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.patient = fieldSetFlags()[1] ? this.patient : (org.naima.avro.patientRecord) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
